In [ ]:
# This is the second python code file used for Ethical Princiles comparison, making use of the AIML techniques.

!pip install --upgrade transformers sentence-transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.32.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.4.26)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)

# 1. Using transformers to calculate cosine similarity between ethical principles

In [ ]:
%cd /content/drive/MyDrive/MLFinanceEthics/

/content/drive/MyDrive/MLFinanceEthics

In [ ]:
!ls

results

In [ ]:
import pandas as pd
from itertools import product

## Read dataset

In [ ]:
# Retrieve long and short definitions of ethical principles in finance and machine learning
# Use the raw file URL from GitHub
fin_dataset = pd.read_excel("https://github.com/shindesagarm/Ethically_Responsible_Machine_Learning_in_Fintech/raw/main/transformers_notebook/dataset_ethics.xlsx",sheet_name='Finance')
ml_dataset = pd.read_excel("https://github.com/shindesagarm/Ethically_Responsible_Machine_Learning_in_Fintech/raw/main/transformers_notebook/dataset_ethics.xlsx",sheet_name='ML')

In [ ]:
# Print the ethical principles of machine learning
ml_dataset.head()

,Principle,Long definition,Short definition
0,"Inclusive growth, sustainable development and ...",This principle states that AI should be develo...,Trustworthy AI should contribute to overall gr...
1,Human-centered values and fairness,"Based on this principle, AI should be develope...",AI systems should be designed in a way that re...
2,Transparency and explainability,Transparency defined in this principle has two...,Transparent and responsible disclosure around ...
3,"Robustness, security and safety",This principle states that AI systems must be ...,"AI systems must function in a robust, secure a..."
4,Accountability,"\nAccording to this principle, organisations a...","Organisations and individuals developing, depl..."

In [ ]:
# Print the ethical principles of finance
fin_dataset.head()

,Principle,Long definition,Short definition
0,Integrity,Acting with integrity is one of the main princ...,"Moral self-governance, autonomy, trustworthine..."
1,Objectivity,Objectivity is ground on the subordination of ...,Protecting and advancing the interests of clie...
2,Competence,Professionals are obligated by to maintain the...,Rendering competent financial services to clie...
3,Fairness,The principle of fairness is an integral part ...,"Treating customers equitably, consistently app..."
4,Confidentiality,Confidentiality is the obligation to hold clie...,"Handling client relationships with confidence,..."

In [ ]:
ds_principles = pd.DataFrame(list(product(fin_dataset['Principle'], ml_dataset['Principle'])),columns=["Finance","ML"])
ds_short_defs = pd.DataFrame(list(product(fin_dataset['Short definition'], ml_dataset['Short definition'])),columns=["Finance","ML"])
ds_long_defs = pd.DataFrame(list(product(fin_dataset['Long definition'], ml_dataset['Long definition'])),columns=["Finance","ML"])

In [ ]:
!pip install transformers
!pip install sentence-transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.52.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.32.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.4.26)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.52.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.32.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.4.26)

In [ ]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

## Define transformer models

In [ ]:
# Define transformer models that will be used in the experiment
models=[
    'sentence-transformers/LaBSE',
    'sentence-transformers/allenai-specter',
    'sentence-transformers/average_word_embeddings_glove.6B.300d',
    'sentence-transformers/average_word_embeddings_glove.840B.300d',
    'sentence-transformers/average_word_embeddings_komninos',
    'sentence-transformers/average_word_embeddings_levy_dependency',
    'sentence-transformers/bert-base-nli-cls-token',
    'sentence-transformers/bert-base-nli-max-tokens',
    'sentence-transformers/bert-base-nli-mean-tokens',
    'sentence-transformers/bert-base-nli-stsb-mean-tokens',
    'sentence-transformers/bert-base-wikipedia-sections-mean-tokens',
    'sentence-transformers/bert-large-nli-cls-token',
    'sentence-transformers/bert-large-nli-max-tokens',
    'sentence-transformers/bert-large-nli-mean-tokens',
    'sentence-transformers/bert-large-nli-stsb-mean-tokens',
    'sentence-transformers/distilbert-base-nli-max-tokens',
    'sentence-transformers/distilbert-base-nli-mean-tokens',
    'sentence-transformers/distilbert-base-nli-stsb-mean-tokens',
    'sentence-transformers/distilbert-base-nli-stsb-quora-ranking',
    'sentence-transformers/distilbert-multilingual-nli-stsb-quora-ranking',
    # Removed distilroberta models that might be problematic
    # 'sentence-transformers/distilroberta-base-msmarco-v1',
    # 'sentence-transformers/distilroberta-base-msmarco-v2',
    # 'sentence-transformers/distilroberta-base-paraphrase-v1',
    'sentence-transformers/distiluse-base-multilingual-cased-v1',
    'sentence-transformers/distiluse-base-multilingual-cased-v2',
    'sentence-transformers/distiluse-base-multilingual-cased',
    'sentence-transformers/facebook-dpr-ctx_encoder-multiset-base',
    'sentence-transformers/facebook-dpr-ctx_encoder-single-nq-base',
    'sentence-transformers/facebook-dpr-question_encoder-multiset-base',
    'sentence-transformers/facebook-dpr-question_encoder-single-nq-base',
    'sentence-transformers/msmarco-MiniLM-L-12-v3',
    'sentence-transformers/msmarco-MiniLM-L-6-v3',
    'sentence-transformers/msmarco-distilbert-base-dot-prod-v3',
    'sentence-transformers/msmarco-distilbert-base-tas-b',
    'sentence-transformers/msmarco-distilbert-base-v2',
    'sentence-transformers/msmarco-distilbert-base-v3',
    'sentence-transformers/msmarco-distilbert-base-v4',
    'sentence-transformers/msmarco-distilbert-multilingual-en-de-v2-tmp-lng-aligned',
    'sentence-transformers/msmarco-distilbert-multilingual-en-de-v2-tmp-trained-scratch',
    # Removed msmarco-distilroberta and msmarco-roberta models
    # 'sentence-transformers/msmarco-distilroberta-base-v2',
    # 'sentence-transformers/msmarco-roberta-base-ance-firstp',
    # 'sentence-transformers/msmarco-roberta-base-v2',
    # 'sentence-transformers/msmarco-roberta-base-v3',
    'sentence-transformers/nli-bert-base-cls-pooling',
    'sentence-transformers/nli-bert-base-max-pooling',
    'sentence-transformers/nli-bert-base',
    'sentence-transformers/nli-bert-large-cls-pooling',
    'sentence-transformers/nli-bert-large-max-pooling',
    'sentence-transformers/nli-bert-large',
    'sentence-transformers/nli-distilbert-base-max-pooling',
    'sentence-transformers/nli-distilbert-base',
    # Removed nli-distilroberta and nli-roberta models
    # 'sentence-transformers/nli-distilroberta-base-v2',
    # 'sentence-transformers/nli-roberta-base-v2',
    # 'sentence-transformers/nli-roberta-base',
    # 'sentence-transformers/nli-roberta-large',
    'sentence-transformers/nli-mpnet-base-v2',
    'sentence-transformers/nq-distilbert-base-v1',
    'sentence-transformers/paraphrase-MiniLM-L12-v2',
    'sentence-transformers/paraphrase-MiniLM-L3-v2',
    'sentence-transformers/paraphrase-MiniLM-L6-v2',
    'sentence-transformers/paraphrase-TinyBERT-L6-v2',
    'sentence-transformers/paraphrase-albert-base-v2',
    'sentence-transformers/paraphrase-albert-small-v2',
    # Removed paraphrase-distilroberta models
    # 'sentence-transformers/paraphrase-distilroberta-base-v1',
    # 'sentence-transformers/paraphrase-distilroberta-base-v2',
    'sentence-transformers/paraphrase-mpnet-base-v2',
    'sentence-transformers/stsb-bert-base',
    'sentence-transformers/stsb-bert-large',
    'sentence-transformers/stsb-distilbert-base',
    # Removed stsb-distilroberta and stsb-roberta models
    # 'sentence-transformers/stsb-distilroberta-base-v2',
    'sentence-transformers/stsb-mpnet-base-v2',
    # 'sentence-transformers/stsb-roberta-base-v2',
    # 'sentence-transformers/stsb-roberta-base',
    # 'sentence-transformers/stsb-roberta-large',
    'sentence-transformers/stsb-xlm-r-multilingual',
    'sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens',
    'sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens',
    'sentence-transformers/xlm-r-bert-base-nli-mean-tokens',
    'sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens',
    # Removed xlm-r-distilroberta model
    # 'sentence-transformers/xlm-r-distilroberta-base-paraphrase-v1',
    'all-mpnet-base-v2'
]

## Calculate cosine similarity across all transformers

In [ ]:
# Calculate cosine similarity between ethical principles across all transformers
from sentence_transformers import SentenceTransformer, util
import numpy as np
import pandas as pd # Ensure pandas is imported for DataFrame operations
from itertools import product # Ensure product is imported if used later

def calc_sim(row, model,label):
  sentence1 = row['Finance']
  sentence2 = row['ML']
  embedding1 = model.encode(sentence1, convert_to_tensor=True)
  embedding2 = model.encode(sentence2, convert_to_tensor=True)
  cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)
  row[label]=cosine_scores.item()
  return row;

In [ ]:
from huggingface_hub import login
login()  # You'll be prompted to paste your token securely | Token: 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

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
# Retrieve long and short definitions of ethical principles in finance and machine learning
# Use the raw file URL from GitHub
fin_dataset = pd.read_excel("https://github.com/shindesagarm/Ethically_Responsible_Machine_Learning_in_Fintech/raw/main/transformers_notebook/dataset_ethics.xlsx",sheet_name='Finance')
ml_dataset = pd.read_excel("https://github.com/shindesagarm/Ethically_Responsible_Machine_Learning_in_Fintech/raw/main/transformers_notebook/dataset_ethics.xlsx",sheet_name='ML')

# Print the ethical principles of machine learning
ml_dataset.head()

# Print the ethical principles of finance
fin_dataset.head()

ds_principles = pd.DataFrame(list(product(fin_dataset['Principle'], ml_dataset['Principle'])),columns=["Finance","ML"])
ds_short_defs = pd.DataFrame(list(product(fin_dataset['Short definition'], ml_dataset['Short definition'])),columns=["Finance","ML"])
ds_long_defs = pd.DataFrame(list(product(fin_dataset['Long definition'], ml_dataset['Long definition'])),columns=["Finance","ML"])

In [ ]:
# Perform the experiment
import os # Import the os module

# Create the 'results' directory if it doesn't exist
if not os.path.exists("./results"):
    os.makedirs("./results")

for model_name in models:
  print("MODEL NAME:"+model_name)
  model = SentenceTransformer(model_name)
  ds_principles = ds_principles.apply(lambda row: calc_sim(row,model,model_name),axis=1)
  ds_short_defs = ds_short_defs.apply(lambda row: calc_sim(row,model,model_name),axis=1)
  ds_long_defs = ds_long_defs.apply(lambda row: calc_sim(row,model,model_name),axis=1)
  ds_principles.to_pickle("./results/ds_principles.pickle")
  ds_short_defs.to_pickle("./results/ds_short_defs.pickle")
  ds_long_defs.to_pickle("./results/ds_long_defs.pickle")

MODEL NAME:sentence-transformers/LaBSE
MODEL NAME:sentence-transformers/allenai-specter
MODEL NAME:sentence-transformers/average_word_embeddings_glove.6B.300d
MODEL NAME:sentence-transformers/average_word_embeddings_glove.840B.300d
MODEL NAME:sentence-transformers/average_word_embeddings_komninos
MODEL NAME:sentence-transformers/average_word_embeddings_levy_dependency
MODEL NAME:sentence-transformers/bert-base-nli-cls-token
MODEL NAME:sentence-transformers/bert-base-nli-max-tokens
MODEL NAME:sentence-transformers/bert-base-nli-mean-tokens
MODEL NAME:sentence-transformers/bert-base-nli-stsb-mean-tokens
MODEL NAME:sentence-transformers/bert-base-wikipedia-sections-mean-tokens
MODEL NAME:sentence-transformers/bert-large-nli-cls-token
MODEL NAME:sentence-transformers/bert-large-nli-max-tokens
MODEL NAME:sentence-transformers/bert-large-nli-mean-tokens
MODEL NAME:sentence-transformers/bert-large-nli-stsb-mean-tokens
MODEL NAME:sentence-transformers/distilbert-base-nli-max-tokens
MODEL NAME:sentence-transformers/distilbert-base-nli-mean-tokens
MODEL NAME:sentence-transformers/distilbert-base-nli-stsb-mean-tokens
MODEL NAME:sentence-transformers/distilbert-base-nli-stsb-quora-ranking
MODEL NAME:sentence-transformers/distilbert-multilingual-nli-stsb-quora-ranking
MODEL NAME:sentence-transformers/distiluse-base-multilingual-cased-v1

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.24k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/556 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/452 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/distiluse-base-multilingual-cased-v2

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.46k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/610 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/531 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/distiluse-base-multilingual-cased

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.16k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/607 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/528 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/rust_model.ot:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/facebook-dpr-ctx_encoder-multiset-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.67k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/668 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/449 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/facebook-dpr-ctx_encoder-single-nq-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.67k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/669 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/450 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/facebook-dpr-question_encoder-multiset-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.69k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/673 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/455 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/facebook-dpr-question_encoder-single-nq-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.69k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/674 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/456 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-MiniLM-L-12-v3

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.72k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/432 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-MiniLM-L-6-v3

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.50k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/430 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-base-dot-prod-v3

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.15k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/554 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2_Dense/pytorch_model.bin:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/115 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-base-tas-b

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.80k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/548 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/547 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-base-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.53k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/545 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/440 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-base-v3

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.53k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/545 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/499 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-base-v4

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.53k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/545 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/319 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-multilingual-en-de-v2-tmp-lng-aligned

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.65k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/501 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/msmarco-distilbert-multilingual-en-de-v2-tmp-trained-scratch

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.67k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/603 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/522 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-bert-base-cls-pooling

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.42k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-bert-base-max-pooling

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.79k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-bert-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.72k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/375 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-bert-large-cls-pooling

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.42k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/401 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-bert-large-max-pooling

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.80k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/401 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-bert-large

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.73k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/377 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-distilbert-base-max-pooling

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.82k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/450 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-distilbert-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.75k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/538 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/426 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nli-mpnet-base-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.49k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/587 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/nq-distilbert-base-v1

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.51k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/540 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/554 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-MiniLM-L12-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.52k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/631 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-MiniLM-L3-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.83k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/69.6M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-MiniLM-L6-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.51k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-TinyBERT-L6-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.52k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/631 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/531 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-albert-base-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.52k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/827 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/46.7M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/464 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/245 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-albert-small-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.84k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/827 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/46.7M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/760k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/245 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/paraphrase-mpnet-base-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.52k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/594 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/stsb-bert-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.73k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/377 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/stsb-bert-large

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.73k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/379 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/stsb-distilbert-base

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.76k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/539 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/489 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/stsb-mpnet-base-v2

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.49k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/588 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/stsb-xlm-r-multilingual

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.52k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/709 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/505 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.84k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/517 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.86k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/731 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/527 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/xlm-r-bert-base-nli-mean-tokens

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.80k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/717 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/508 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.82k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/722 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/518 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

MODEL NAME:all-mpnet-base-v2

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# Load the dataframes from the pickle files
import pandas as pd
ds_principles = pd.read_pickle("./results/ds_principles.pickle")
ds_short_defs = pd.read_pickle("./results/ds_short_defs.pickle")
ds_long_defs = pd.read_pickle("./results/ds_long_defs.pickle")

In [ ]:
ds_principles = ds_principles.apply(lambda row: calc_sim(row,model,'stsb-roberta-large'),axis=1)
ds_short_defs = ds_short_defs.apply(lambda row: calc_sim(row,model,'stsb-roberta-large'),axis=1)
ds_long_defs = ds_long_defs.apply(lambda row: calc_sim(row,model,'stsb-roberta-large'),axis=1)

In [ ]:
ds_short_defs.head()

,Finance,ML,sentence-transformers/LaBSE,sentence-transformers/allenai-specter,sentence-transformers/average_word_embeddings_glove.6B.300d,sentence-transformers/average_word_embeddings_glove.840B.300d,sentence-transformers/average_word_embeddings_komninos,sentence-transformers/average_word_embeddings_levy_dependency,sentence-transformers/bert-base-nli-cls-token,sentence-transformers/bert-base-nli-max-tokens,...,sentence-transformers/stsb-bert-large,sentence-transformers/stsb-distilbert-base,sentence-transformers/stsb-mpnet-base-v2,sentence-transformers/stsb-xlm-r-multilingual,sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens,all-mpnet-base-v2,stsb-roberta-large
0,"Moral self-governance, autonomy, trustworthine...",Trustworthy AI should contribute to overall gr...,0.313011,0.788788,0.525359,0.571049,0.720031,0.788346,0.641809,0.726695,...,0.288724,0.374110,0.298516,0.539144,0.610239,0.539144,0.610239,0.539144,0.261389,0.261389
1,"Moral self-governance, autonomy, trustworthine...",AI systems should be designed in a way that re...,0.467257,0.782522,0.678282,0.629304,0.748433,0.814385,0.789429,0.825633,...,0.372820,0.454450,0.419768,0.692615,0.770124,0.692615,0.770124,0.692615,0.343338,0.343338
2,"Moral self-governance, autonomy, trustworthine...",Transparent and responsible disclosure around ...,0.247537,0.769408,0.690555,0.606090,0.734101,0.805628,0.640556,0.779143,...,0.297339,0.395391,0.267380,0.528633,0.638603,0.528633,0.638603,0.528633,0.150961,0.150961
3,"Moral self-governance, autonomy, trustworthine...","AI systems must function in a robust, secure a...",0.460776,0.731835,0.541990,0.516778,0.677451,0.766192,0.777567,0.832375,...,0.371651,0.429193,0.307733,0.607098,0.699053,0.607098,0.699053,0.607098,0.192022,0.192022
4,"Moral self-governance, autonomy, trustworthine...","Organisations and individuals developing, depl...",0.394821,0.692191,0.603914,0.575362,0.713081,0.761288,0.719702,0.773743,...,0.503029,0.454105,0.465263,0.595025,0.655949,0.595025,0.655949,0.595025,0.277417,0.277417

## Save Results

In [ ]:
import pandas as pd
ds_principles = pd.read_pickle("/content/results/ds_principles.pickle")
ds_long_defs = pd.read_pickle("/content/results/ds_long_defs.pickle")
ds_short_defs = pd.read_pickle("/content/results/ds_short_defs.pickle")

In [ ]:
# Save the results
ds_principles.to_excel("ds_principles.xlsx")
ds_long_defs.to_excel("ds_long_defs.xlsx")
ds_short_defs.to_excel("ds_short_defs.xlsx")

# 2. Comparison between ethical principles of finance and machine learning

## Long and short definitions of ethical principles

In [ ]:
long_defs = pd.read_excel('/content/ds_long_defs.xlsx')

In [ ]:
long_defs.drop(labels=['Unnamed: 0'], axis=1, inplace=True)

In [ ]:
long_defs

,Finance,ML,sentence-transformers/LaBSE,sentence-transformers/allenai-specter,sentence-transformers/average_word_embeddings_glove.6B.300d,sentence-transformers/average_word_embeddings_glove.840B.300d,sentence-transformers/average_word_embeddings_komninos,sentence-transformers/average_word_embeddings_levy_dependency,sentence-transformers/bert-base-nli-cls-token,sentence-transformers/bert-base-nli-max-tokens,...,sentence-transformers/stsb-bert-base,sentence-transformers/stsb-bert-large,sentence-transformers/stsb-distilbert-base,sentence-transformers/stsb-mpnet-base-v2,sentence-transformers/stsb-xlm-r-multilingual,sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens,all-mpnet-base-v2
0,Acting with integrity is one of the main princ...,This principle states that AI should be develo...,0.387797,0.680879,0.667160,0.801566,0.824382,0.888240,0.612051,0.832134,...,0.437207,0.306911,0.286527,0.307816,0.413045,0.574273,0.413045,0.574273,0.413045,0.400738
1,Acting with integrity is one of the main princ...,"Based on this principle, AI should be develope...",0.518087,0.745447,0.815029,0.876798,0.888299,0.919479,0.730444,0.870335,...,0.620114,0.472762,0.516077,0.440790,0.637795,0.719439,0.637795,0.719439,0.637795,0.449621
2,Acting with integrity is one of the main princ...,Transparency defined in this principle has two...,0.377956,0.721432,0.716568,0.808795,0.811049,0.870325,0.580073,0.824998,...,0.454645,0.379245,0.365446,0.302299,0.454105,0.606151,0.454105,0.606151,0.454105,0.328345
3,Acting with integrity is one of the main princ...,This principle states that AI systems must be ...,0.493411,0.734399,0.723158,0.804302,0.822913,0.890237,0.733217,0.861202,...,0.673234,0.506182,0.582923,0.336424,0.667177,0.750001,0.667177,0.750001,0.667177,0.341357
4,Acting with integrity is one of the main princ...,"\nAccording to this principle, organisations a...",0.467611,0.766570,0.804600,0.867506,0.871983,0.897001,0.717485,0.851612,...,0.657306,0.588505,0.502478,0.468255,0.638409,0.723817,0.638409,0.723817,0.638409,0.406102
5,Objectivity is ground on the subordination of ...,This principle states that AI should be develo...,0.411490,0.648432,0.786892,0.872619,0.881101,0.920371,0.493207,0.822241,...,0.396640,0.356030,0.368659,0.334680,0.446310,0.564351,0.446310,0.564351,0.446310,0.306452
6,Objectivity is ground on the subordination of ...,"Based on this principle, AI should be develope...",0.523553,0.724341,0.832492,0.899356,0.888390,0.911563,0.549102,0.839616,...,0.444221,0.456044,0.379541,0.500065,0.514107,0.636266,0.514107,0.636266,0.514107,0.316687
7,Objectivity is ground on the subordination of ...,Transparency defined in this principle has two...,0.480815,0.704957,0.818543,0.856226,0.863574,0.890038,0.552281,0.803626,...,0.437235,0.461033,0.316642,0.276035,0.456469,0.547271,0.456469,0.547271,0.456469,0.290271
8,Objectivity is ground on the subordination of ...,This principle states that AI systems must be ...,0.454111,0.669547,0.797848,0.854988,0.875549,0.911830,0.410457,0.768204,...,0.402887,0.403756,0.341494,0.243800,0.404855,0.450496,0.404855,0.450496,0.404855,0.259552
9,Objectivity is ground on the subordination of ...,"\nAccording to this principle, organisations a...",0.423634,0.698199,0.789235,0.870432,0.876405,0.894781,0.459548,0.748360,...,0.410678,0.392627,0.344620,0.302483,0.443657,0.524740,0.443657,0.524740,0.443657,0.288626
10,Professionals are obligated by to maintain the...,This principle states that AI should be develo...,0.396131,0.643295,0.783545,0.855702,0.852133,0.902574,0.523049,0.836675,...,0.449765,0.356227,0.344097,0.334651,0.500404,0.619282,0.500404,0.619282,0.500404,0.241308
11,Professionals are obligated by to maintain the...,"Based on this principle, AI should be develope...",0.519363,0.689299,0.779926,0.837226,0.842115,0.877082,0.580539,0.845281,...,0.433282,0.500130,0.379094,0.309597,0.529006,0.654672,0.529006,0.654672,0.529006,0.235953
12,Professionals are obligated by to maintain the...,Transparency defined in this principle has two...,0.508354,0.659013,0.817066,0.859757,0.853009,0.880335,0.605481,0.828665,...,0.454078,0.471190,0.346451,0.311906,0.481758,0.631271,0.481758,0.631271,0.481758,0.228736
13,Professionals are obligated by to maintain the...,This principle states that AI systems must be ...,0.481992,0.668104,0.799463,0.869349,0.858821,0.896966,0.552412,0.824087,...,0.471796,0.528165,0.465331,0.276790,0.513673,0.568808,0.513673,0.568808,0.513673,0.237345
14,Professionals are obligated by to maintain the...,"\nAccording to this principle, organisations a...",0.434091,0.692124,0.795962,0.878085,0.864081,0.893678,0.531342,0.773301,...,0.431623,0.457201,0.363921,0.280625,0.504697,0.590030,0.504697,0.590030,0.504697,0.268966
15,The principle of fairness is an integral part ...,This principle states that AI should be develo...,0.377218,0.696143,0.788757,0.852291,0.868632,0.907190,0.697922,0.878344,...,0.575998,0.377725,0.429568,0.416320,0.569685,0.706058,0.569685,0.706058,0.569685,0.428375
16,The principle of fairness is an integral part ...,"Based on this principle, AI should be develope...",0.571148,0.761949,0.876205,0.899526,0.917476,0.931989,0.765658,0.895091,...,0.662745,0.568360,0.553376,0.484324,0.653972,0.748635,0.653972,0.748635,0.653972,0.487861
17,The principle of fairness is an integral part ...,Transparency defined in this principle has two...,0.527113,0.719124,0.855138,0.876906,0.892529,0.919242,0.639056,0.859988,...,0.560580,0.485105,0.536863,0.310518,0.598664,0.682508,0.598664,0.682508,0.598664,0.306430
18,The principle of fairness is an integral part ...,This principle states that AI systems must be ...,0.448809,0.682908,0.808079,0.853272,0.873023,0.909112,0.697859,0.871233,...,0.605285,0.474661,0.535701,0.252944,0.550799,0.705825,0.550799,0.705825,0.550799,0.285045
19,The principle of fairness is an integral part ...,"\nAccording to this principle, organisations a...",0.416789,0.695077,0.833516,0.887035,0.906211,0.917947,0.686905,0.849305,...,0.589801,0.538310,0.560424,0.327871,0.566741,0.699886,0.566741,0.699886,0.566741,0.306713
20,Confidentiality is the obligation to hold clie...,This principle states that AI should be develo...,0.399282,0.610054,0.725971,0.807737,0.824045,0.894624,0.557856,0.836410,...,0.336394,0.297476,0.249676,0.191805,0.346306,0.566580,0.346306,0.566580,0.346306,0.315044
21,Confidentiality is the obligation to hold clie...,"Based on this principle, AI should be develope...",0.575787,0.693707,0.788688,0.831545,0.864030,0.908620,0.676289,0.861323,...,0.392639,0.427226,0.367482,0.283147,0.458944,0.692162,0.458944,0.692162,0.458944,0.329011
22,Confidentiality is the obligation to hold clie...,Transparency defined in this principle has two...,0.560702,0.670429,0.805516,0.837915,0.833823,0.880732,0.645617,0.841533,...,0.403150,0.350859,0.487320,0.272232,0.434381,0.628698,0.434381,0.628698,0.434381,0.310151
23,Confidentiality is the obligation to hold clie...,This principle states that AI systems must be ...,0.550384,0.668360,0.774053,0.827060,0.849310,0.898781,0.652790,0.841960,...,0.445138,0.466123,0.464684,0.315320,0.503753,0.667660,0.503753,0.667660,0.503753,0.361921
24,Confidentiality is the obligation to hold clie...,"\nAccording to this principle, organisations a...",0.458021,0.671581,0.759078,0.827693,0.852390,0.895488,0.625168,0.791719,...,0.385402,0.376798,0.345940,0.290213,0.447112,0.619229,0.447112,0.619229,0.447112,0.271406
25,The principle of professionalism has three req...,This principle states that AI should be develo...,0.435544,0.667657,0.795015,0.868869,0.871473,0.909479,0.610964,0.863820,...,0.497046,0.393325,0.380011,0.283789,0.467218,0.618654,0.467218,0.618654,0.467218,0.356355
26,The principle of professionalism has three req...,"Based on this principle, AI should be develope...",0.573639,0.717343,0.812794,0.852774,0.864665,0.898560,0.681942,0.867225,...,0.545416,0.456257,0.444593,0.384669,0.581282,0.708709,0.581282,0.708709,0.581282,0.323881
27,The principle of professionalism has three req...,Transparency defined in this principle has two...,0.510459,0.677520,0.822571,0.854255,0.860571,0.891097,0.670423,0.844952,...,0.518139,0.400991,0.458524,0.156996,0.518046,0.639362,0.518046,0.639362,0.518046,0.226797
28,The principle of professionalism has three req...,This principle states that AI systems must be ...,0.492478,0.673038,0.800098,0.867625,0.865607,0.896888,0.622087,0.835837,...,0.583049,0.417215,0.516259,0.218935,0.568052,0.658245,0.568052,0.658245,0.568052,0.258775
29,The principle of professionalism has three req...,"\nAccording to this principle, organisations a...",0.437306,0.701287,0.830100,0.891052,0.891835,0.911730,0.608002,0.794908,...,0.553027,0.368524,0.450080,0.288491,0.557806,0.653200,0.557806,0.653200,0.557806,0.275614
30,The ethical principle of diligence can be inte...,This principle states that AI should be develo...,0.372550,0.659889,0.749133,0.812119,0.837142,0.886954,0.568155,0.844734,...,0.480763,0.322639,0.378300,0.218364,0.455723,0.579422,0.455723,0.579422,0.455723,0.359211
31,The ethical principle of diligence can be inte...,"Based on this principle, AI should be develope...",0.495498,0.692301,0.794760,0.825524,0.850706,0.891262,0.661539,0.859801,...,0.581257,0.514865,0.458773,0.366562,0.579308,0.676184,0.579308,0.676184,0.579308,0.414879
32,The ethical principle of diligence can be inte...,Transparency defined in this principle has two...,0.586994,0.653070,0.851004,0.865389,0.876645,0.900307,0.677114,0.861742,...,0.542693,0.509796,0.484627,0.283255,0.560667,0.662769,0.560667,0.662769,0.560667,0.288198
33,The ethical principle of diligence can be inte...,This principle states that AI systems must be ...,0.519546,0.647792,0.824921,0.856493,0.876702,0.915653,0.641540,0.840057,...,0.649897,0.502916,0.502971,0.314547,0.591649,0.642976,0.591649,0.642976,0.591649,0.328390
34,The ethical principle of diligence can be inte...,"\nAccording to this principle, organisations a...",0.445759,0.698684,0.831425,0.868603,0.889833,0.902469,0.708716,0.843251,...,0.663897,0.567076,0.542501,0.461176,0.658198,0.691546,0.658198,0.691546,0.658198,0.329394

In [ ]:
short_defs = pd.read_excel('/content/ds_short_defs.xlsx')

In [ ]:
short_defs.drop(labels=['Unnamed: 0'], axis=1, inplace=True)

In [ ]:
short_defs

,Finance,ML,sentence-transformers/LaBSE,sentence-transformers/allenai-specter,sentence-transformers/average_word_embeddings_glove.6B.300d,sentence-transformers/average_word_embeddings_glove.840B.300d,sentence-transformers/average_word_embeddings_komninos,sentence-transformers/average_word_embeddings_levy_dependency,sentence-transformers/bert-base-nli-cls-token,sentence-transformers/bert-base-nli-max-tokens,...,sentence-transformers/stsb-bert-base,sentence-transformers/stsb-bert-large,sentence-transformers/stsb-distilbert-base,sentence-transformers/stsb-mpnet-base-v2,sentence-transformers/stsb-xlm-r-multilingual,sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens,all-mpnet-base-v2
0,"Moral self-governance, autonomy, trustworthine...",Trustworthy AI should contribute to overall gr...,0.313011,0.788788,0.525359,0.571049,0.720031,0.788346,0.641809,0.726695,...,0.537367,0.288724,0.374110,0.298516,0.539144,0.610239,0.539144,0.610239,0.539144,0.261389
1,"Moral self-governance, autonomy, trustworthine...",AI systems should be designed in a way that re...,0.467257,0.782522,0.678282,0.629304,0.748433,0.814385,0.789429,0.825633,...,0.666821,0.372820,0.454450,0.419768,0.692615,0.770124,0.692615,0.770124,0.692615,0.343338
2,"Moral self-governance, autonomy, trustworthine...",Transparent and responsible disclosure around ...,0.247537,0.769408,0.690555,0.606090,0.734101,0.805628,0.640556,0.779143,...,0.477818,0.297339,0.395391,0.267380,0.528633,0.638603,0.528633,0.638603,0.528633,0.150961
3,"Moral self-governance, autonomy, trustworthine...","AI systems must function in a robust, secure a...",0.460776,0.731835,0.541990,0.516778,0.677451,0.766192,0.777567,0.832375,...,0.605844,0.371651,0.429193,0.307733,0.607098,0.699053,0.607098,0.699053,0.607098,0.192022
4,"Moral self-governance, autonomy, trustworthine...","Organisations and individuals developing, depl...",0.394821,0.692191,0.603914,0.575362,0.713081,0.761288,0.719702,0.773743,...,0.578754,0.503029,0.454105,0.465263,0.595025,0.655949,0.595025,0.655949,0.595025,0.277417
5,Protecting and advancing the interests of clie...,Trustworthy AI should contribute to overall gr...,0.275948,0.686387,0.631883,0.620607,0.740241,0.786778,0.677746,0.767499,...,0.566329,0.289010,0.410620,0.339240,0.573393,0.627063,0.573393,0.627063,0.573393,0.209061
6,Protecting and advancing the interests of clie...,AI systems should be designed in a way that re...,0.376138,0.660218,0.698955,0.655111,0.770104,0.796319,0.802878,0.850157,...,0.631140,0.480059,0.466100,0.446789,0.628684,0.747726,0.628684,0.747726,0.628684,0.227346
7,Protecting and advancing the interests of clie...,Transparent and responsible disclosure around ...,0.286285,0.740660,0.710319,0.655117,0.806400,0.812329,0.761210,0.844590,...,0.532332,0.383676,0.479040,0.324011,0.561120,0.710181,0.561120,0.710181,0.561120,0.251653
8,Protecting and advancing the interests of clie...,"AI systems must function in a robust, secure a...",0.356274,0.655359,0.647909,0.598936,0.729477,0.754630,0.738885,0.825178,...,0.596382,0.399574,0.468508,0.356433,0.603764,0.717859,0.603764,0.717859,0.603764,0.172552
9,Protecting and advancing the interests of clie...,"Organisations and individuals developing, depl...",0.246275,0.674180,0.609709,0.640476,0.762010,0.799814,0.751375,0.816452,...,0.545596,0.337371,0.453538,0.378564,0.532946,0.683132,0.532946,0.683132,0.532946,0.226106
10,Rendering competent financial services to clie...,Trustworthy AI should contribute to overall gr...,0.169171,0.590551,0.653258,0.722751,0.738911,0.784886,0.585588,0.775807,...,0.503232,0.401885,0.335337,0.276720,0.524555,0.614421,0.524555,0.614421,0.524555,0.159235
11,Rendering competent financial services to clie...,AI systems should be designed in a way that re...,0.190602,0.550216,0.691122,0.706013,0.750988,0.786310,0.568998,0.744751,...,0.353908,0.357808,0.193437,0.233959,0.392979,0.527866,0.392979,0.527866,0.392979,0.118735
12,Rendering competent financial services to clie...,Transparent and responsible disclosure around ...,0.240084,0.653504,0.741875,0.748961,0.773452,0.797320,0.642204,0.757462,...,0.485907,0.469994,0.400371,0.141182,0.538636,0.622257,0.538636,0.622257,0.538636,0.190383
13,Rendering competent financial services to clie...,"AI systems must function in a robust, secure a...",0.302727,0.571169,0.680432,0.720806,0.744849,0.779149,0.631788,0.778630,...,0.525894,0.530703,0.422229,0.350972,0.604137,0.659731,0.604137,0.659731,0.604137,0.134589
14,Rendering competent financial services to clie...,"Organisations and individuals developing, depl...",0.228899,0.636956,0.689868,0.743997,0.769877,0.799582,0.679005,0.778450,...,0.529541,0.490134,0.444615,0.262582,0.533973,0.635907,0.533973,0.635907,0.533973,0.178235
15,"Treating customers equitably, consistently app...",Trustworthy AI should contribute to overall gr...,0.245896,0.692156,0.520918,0.641318,0.715486,0.782636,0.709926,0.794263,...,0.458972,0.219586,0.366571,0.258573,0.553032,0.701042,0.553032,0.701042,0.553032,0.124409
16,"Treating customers equitably, consistently app...",AI systems should be designed in a way that re...,0.416099,0.722295,0.696788,0.741412,0.798169,0.839477,0.735288,0.795478,...,0.525929,0.300799,0.416555,0.351977,0.538028,0.693978,0.538028,0.693978,0.538028,0.234477
17,"Treating customers equitably, consistently app...",Transparent and responsible disclosure around ...,0.247976,0.721972,0.707067,0.721608,0.814993,0.844844,0.614635,0.746074,...,0.444406,0.209821,0.369582,0.191397,0.474180,0.634163,0.474180,0.634163,0.474180,0.142440
18,"Treating customers equitably, consistently app...","AI systems must function in a robust, secure a...",0.289033,0.693546,0.662033,0.715862,0.781680,0.825989,0.712723,0.817353,...,0.473799,0.308946,0.416720,0.191667,0.512001,0.690733,0.512001,0.690733,0.512001,0.100381
19,"Treating customers equitably, consistently app...","Organisations and individuals developing, depl...",0.290327,0.671950,0.582602,0.671912,0.770563,0.809654,0.654520,0.751501,...,0.408386,0.197746,0.331577,0.267733,0.373963,0.570673,0.373963,0.570673,0.373963,0.207726
20,"Handling client relationships with confidence,...",Trustworthy AI should contribute to overall gr...,0.252568,0.630770,0.585467,0.682655,0.687670,0.760572,0.629075,0.715334,...,0.536322,0.360703,0.400069,0.194887,0.544062,0.581277,0.544062,0.581277,0.544062,0.279885
21,"Handling client relationships with confidence,...",AI systems should be designed in a way that re...,0.346519,0.645696,0.681343,0.734834,0.729379,0.786522,0.742855,0.794420,...,0.464042,0.394626,0.349036,0.225603,0.482844,0.662339,0.482844,0.662339,0.482844,0.191201
22,"Handling client relationships with confidence,...",Transparent and responsible disclosure around ...,0.334974,0.760074,0.722570,0.780385,0.792921,0.834974,0.743320,0.815121,...,0.577671,0.466734,0.494883,0.269962,0.607516,0.705671,0.607516,0.705671,0.607516,0.256969
23,"Handling client relationships with confidence,...","AI systems must function in a robust, secure a...",0.431106,0.688389,0.685799,0.776119,0.731377,0.768775,0.741077,0.826506,...,0.559292,0.488579,0.436653,0.289854,0.580152,0.692026,0.580152,0.692026,0.580152,0.253188
24,"Handling client relationships with confidence,...","Organisations and individuals developing, depl...",0.287753,0.681044,0.653750,0.728132,0.735700,0.806189,0.723187,0.771852,...,0.482695,0.354672,0.373765,0.218664,0.440934,0.624955,0.440934,0.624955,0.440934,0.193873
25,"Treating clients with courtesy and respect, es...",Trustworthy AI should contribute to overall gr...,0.401665,0.658174,0.609161,0.696287,0.706635,0.755968,0.659342,0.750020,...,0.571383,0.302330,0.360501,0.239689,0.543428,0.630047,0.543428,0.630047,0.543428,0.159925
26,"Treating clients with courtesy and respect, es...",AI systems should be designed in a way that re...,0.393493,0.671015,0.712155,0.730952,0.729708,0.772864,0.711217,0.786955,...,0.508000,0.288243,0.379865,0.259391,0.486883,0.634762,0.486883,0.634762,0.486883,0.174888
27,"Treating clients with courtesy and respect, es...",Transparent and responsible disclosure around ...,0.229894,0.722378,0.690081,0.737424,0.728341,0.782376,0.649374,0.757389,...,0.465926,0.257663,0.410642,0.174688,0.471588,0.610652,0.471588,0.610652,0.471588,0.149170
28,"Treating clients with courtesy and respect, es...","AI systems must function in a robust, secure a...",0.336415,0.672994,0.637147,0.720115,0.685334,0.733981,0.672669,0.801209,...,0.519430,0.287504,0.392069,0.171557,0.528002,0.641326,0.528002,0.641326,0.528002,0.119025
29,"Treating clients with courtesy and respect, es...","Organisations and individuals developing, depl...",0.292932,0.660613,0.630954,0.696680,0.714768,0.778827,0.659014,0.744829,...,0.470621,0.243687,0.429015,0.262734,0.410349,0.563464,0.410349,0.563464,0.410349,0.177345
30,"Providing services promptly and thoroughly, re...",Trustworthy AI should contribute to overall gr...,0.248425,0.623326,0.572749,0.705114,0.714599,0.772045,0.621952,0.747955,...,0.517365,0.296668,0.436084,0.145869,0.535736,0.657129,0.535736,0.657129,0.535736,0.057066
31,"Providing services promptly and thoroughly, re...",AI systems should be designed in a way that re...,0.317660,0.646035,0.683128,0.727202,0.753092,0.784259,0.639078,0.760085,...,0.394581,0.288302,0.298104,0.145208,0.430257,0.573810,0.430257,0.573810,0.430257,0.127042
32,"Providing services promptly and thoroughly, re...",Transparent and responsible disclosure around ...,0.279573,0.733565,0.725192,0.789296,0.773735,0.816594,0.725402,0.821061,...,0.629682,0.455534,0.515942,0.170698,0.674010,0.736725,0.674010,0.736725,0.674010,0.125164
33,"Providing services promptly and thoroughly, re...","AI systems must function in a robust, secure a...",0.326171,0.664771,0.674785,0.777876,0.749177,0.801623,0.757460,0.834524,...,0.644779,0.495539,0.540914,0.158978,0.691897,0.734040,0.691897,0.734040,0.691897,0.121338
34,"Providing services promptly and thoroughly, re...","Organisations and individuals developing, depl...",0.326676,0.676225,0.629179,0.726473,0.740636,0.755449,0.730984,0.809439,...,0.631820,0.427261,0.527135,0.223004,0.640978,0.706136,0.640978,0.706136,0.640978,0.181172

## Helper functions

In [ ]:
# Calculate percentiles
def get_percentile(dataset, column, percentile):
  return np.percentile(dataset[column].values, percentile)

In [ ]:
# Annotate relationship based on percentiles
def annotate_strength_relationship(dataset):
  new_dataset = pd.DataFrame()

  for column in dataset.columns:
    l = []
    percentile33 = get_percentile(dataset, column, 33.333)
    percentile66 = get_percentile(dataset, column, 66.666)

    for item in dataset[column].values:
      if item <= percentile33:
        l.append(0)
      elif item <= percentile66:
        l.append(1)
      else:
        l.append(2)

    new_dataset[column] = np.asarray(l)

  return new_dataset

## Mappings between the ethical principles based on long and short definitions

In [ ]:
links_long = annotate_strength_relationship(long_defs.iloc[:,2:])

In [ ]:
links_long

,sentence-transformers/LaBSE,sentence-transformers/allenai-specter,sentence-transformers/average_word_embeddings_glove.6B.300d,sentence-transformers/average_word_embeddings_glove.840B.300d,sentence-transformers/average_word_embeddings_komninos,sentence-transformers/average_word_embeddings_levy_dependency,sentence-transformers/bert-base-nli-cls-token,sentence-transformers/bert-base-nli-max-tokens,sentence-transformers/bert-base-nli-mean-tokens,sentence-transformers/bert-base-nli-stsb-mean-tokens,...,sentence-transformers/stsb-bert-base,sentence-transformers/stsb-bert-large,sentence-transformers/stsb-distilbert-base,sentence-transformers/stsb-mpnet-base-v2,sentence-transformers/stsb-xlm-r-multilingual,sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens,all-mpnet-base-v2
0,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,2
1,2,2,2,2,2,2,2,2,2,2,...,2,1,2,2,2,2,2,2,2,2
2,0,2,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,0,0,0,1
3,1,2,0,0,0,0,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
4,1,2,1,1,1,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
5,0,0,0,2,2,2,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
6,2,2,2,2,2,2,0,1,0,0,...,0,1,1,2,1,1,1,1,1,1
7,1,2,2,1,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
8,1,0,1,1,2,2,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,0,2,1,2,2,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
10,0,0,0,1,0,1,0,1,0,1,...,1,0,0,2,1,1,1,1,1,0
11,2,1,0,0,0,0,0,1,0,0,...,0,2,1,1,1,1,1,1,1,0
12,1,0,2,1,0,0,1,0,1,1,...,1,1,0,1,1,1,1,1,1,0
13,1,0,1,2,1,1,0,0,1,1,...,1,2,1,0,1,0,1,0,1,0
14,0,1,1,2,1,0,0,0,0,0,...,0,1,0,0,1,0,1,0,1,0
15,0,1,0,0,1,1,2,2,1,2,...,2,0,1,2,2,2,2,2,2,2
16,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
17,2,2,2,2,2,2,1,2,1,2,...,2,2,2,1,2,2,2,2,2,1
18,1,1,1,1,1,2,2,2,2,2,...,2,2,2,0,1,2,1,2,1,0
19,0,1,2,2,2,2,2,1,2,2,...,2,2,2,2,2,2,2,2,2,1
20,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
21,2,1,0,0,1,2,2,2,1,0,...,0,1,0,0,0,2,0,2,0,2
22,2,0,1,0,0,0,1,1,1,0,...,0,0,2,0,0,1,0,1,0,1
23,2,0,0,0,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
24,1,1,0,0,0,1,1,0,1,0,...,0,0,0,1,0,0,0,0,0,0
25,0,0,1,2,1,2,1,2,1,1,...,1,0,1,1,0,0,0,0,0,2
26,2,2,1,1,1,1,2,2,2,1,...,1,1,1,2,2,2,2,2,2,1
27,2,1,2,1,1,0,2,1,1,1,...,1,1,1,0,1,1,1,1,1,0
28,1,1,1,1,1,1,1,0,2,2,...,2,1,2,0,2,1,2,1,2,0
29,0,2,2,2,2,2,1,0,1,1,...,1,0,1,1,1,1,1,1,1,0
30,0,0,0,0,0,0,0,1,0,1,...,1,0,1,0,0,0,0,0,0,2
31,1,1,1,0,0,0,1,2,2,2,...,2,2,1,2,2,2,2,2,2,2
32,2,0,2,1,2,1,2,2,2,1,...,1,2,2,0,1,1,1,1,1,0
33,2,0,2,1,2,2,1,1,2,2,...,2,2,2,1,2,1,2,1,2,1
34,1,2,2,2,2,1,2,1,2,2,...,2,2,2,2,2,2,2,2,2,2

In [ ]:
links_short = annotate_strength_relationship(short_defs.iloc[:,2:])

In [ ]:
links_short

,sentence-transformers/LaBSE,sentence-transformers/allenai-specter,sentence-transformers/average_word_embeddings_glove.6B.300d,sentence-transformers/average_word_embeddings_glove.840B.300d,sentence-transformers/average_word_embeddings_komninos,sentence-transformers/average_word_embeddings_levy_dependency,sentence-transformers/bert-base-nli-cls-token,sentence-transformers/bert-base-nli-max-tokens,sentence-transformers/bert-base-nli-mean-tokens,sentence-transformers/bert-base-nli-stsb-mean-tokens,...,sentence-transformers/stsb-bert-base,sentence-transformers/stsb-bert-large,sentence-transformers/stsb-distilbert-base,sentence-transformers/stsb-mpnet-base-v2,sentence-transformers/stsb-xlm-r-multilingual,sentence-transformers/xlm-r-100langs-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-mean-tokens,sentence-transformers/xlm-r-bert-base-nli-stsb-mean-tokens,all-mpnet-base-v2
0,1,2,0,0,0,1,0,0,0,1,...,1,0,0,2,1,0,1,0,1,2
1,2,2,1,0,1,2,2,2,2,2,...,2,1,2,2,2,2,2,2,2,2
2,0,2,2,0,1,2,0,1,0,0,...,0,0,1,1,1,1,1,1,1,0
3,2,2,0,0,0,0,2,2,2,2,...,2,1,1,2,2,2,2,2,2,1
4,2,2,0,0,0,0,1,1,1,2,...,2,2,2,2,2,1,2,1,2,2
5,0,1,0,0,1,1,1,0,1,2,...,2,0,1,2,2,0,2,0,2,2
6,2,0,2,0,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
7,1,2,2,0,2,2,2,2,2,1,...,1,1,2,2,1,2,1,2,1,2
8,2,0,1,0,0,0,2,2,2,2,...,2,2,2,2,2,2,2,2,2,1
9,0,1,0,0,2,2,2,2,2,1,...,1,1,2,2,1,1,1,1,1,2
10,0,0,1,1,1,1,0,1,0,1,...,1,2,0,1,0,0,0,0,0,1
11,0,0,2,1,1,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
12,0,0,2,2,2,1,0,0,0,0,...,0,2,1,0,1,0,1,0,1,1
13,1,0,1,1,1,0,0,1,1,1,...,1,2,1,2,2,1,2,1,2,0
14,0,0,2,2,2,1,1,1,1,1,...,1,2,2,1,1,1,1,1,1,1
15,0,1,0,0,0,1,1,1,2,0,...,0,0,0,1,1,2,1,2,1,0
16,2,2,2,2,2,2,2,1,1,1,...,1,1,1,2,1,2,1,2,1,2
17,0,2,2,1,2,2,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
18,1,2,1,1,2,2,1,2,1,0,...,0,1,1,0,0,1,0,1,0,0
19,1,1,0,0,2,2,0,0,0,0,...,0,0,0,1,0,0,0,0,0,2
20,0,0,0,1,0,0,0,0,0,1,...,1,1,1,0,1,0,1,0,1,2
21,2,0,1,2,0,1,2,1,1,0,...,0,1,0,1,0,1,0,1,0,1
22,2,2,2,2,2,2,2,2,2,2,...,2,2,2,1,2,2,2,2,2,2
23,2,1,1,2,1,0,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
24,1,1,1,2,1,2,1,1,1,0,...,0,1,0,0,0,0,0,0,0,1
25,2,0,0,1,0,0,1,0,1,2,...,2,1,0,1,1,0,1,0,1,1
26,2,1,2,2,1,0,1,1,1,1,...,1,0,0,1,0,1,0,1,0,1
27,0,2,2,2,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,2,1,1,1,0,0,1,1,1,1,...,1,0,0,0,0,1,0,1,0,0
29,1,1,0,1,0,0,1,0,0,0,...,0,0,1,1,0,0,0,0,0,1
30,0,0,0,1,0,0,0,0,0,1,...,1,0,1,0,1,1,1,1,1,0
31,1,0,1,2,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,1,2,2,2,2,2,1,2,2,2,...,2,2,2,0,2,2,2,2,2,0
33,1,1,1,2,1,2,2,2,2,2,...,2,2,2,0,2,2,2,2,2,0
34,1,1,0,1,1,0,2,2,2,2,...,2,2,2,0,2,2,2,2,2,1

## Determine overlaps across all transformers

In [ ]:
# Calculate the number of overlaps between long and short mappings for each transformer
def calculate_overlaps(long_links, short_links):
  # Use a list to store new data rows
  new_data_list = []

  for column in long_links.columns:
    num_overlaps = (short_links[column].values == long_links[column].values).sum()
    new_data = {'transformer': column, 'number of overlaps': num_overlaps}
    # Append the new data as a dictionary to the list
    new_data_list.append(new_data)

  # Concatenate the list of dictionaries into a DataFrame after the loop
  overlaps = pd.DataFrame(new_data_list)

  return overlaps

In [ ]:
overlaps = calculate_overlaps(links_long, links_short)

In [ ]:
overlaps.sort_values(by=['number of overlaps'], ascending=False, inplace=True, ignore_index=True)

In [ ]:
overlaps

                                          transformer  number of overlaps
0                         sentence-transformers/LaBSE                  21
1    sentence-transformers/bert-large-nli-mean-tokens                  20
2                sentence-transformers/nli-bert-large                  20
3   sentence-transformers/distilroberta-base-msmar...                  19
4   sentence-transformers/average_word_embeddings_...                  18
..                                                ...                 ...
60  sentence-transformers/facebook-dpr-question_en...                   8
61        sentence-transformers/nq-distilbert-base-v1                   8
62  sentence-transformers/msmarco-distilbert-base-...                   7
63  sentence-transformers/facebook-dpr-ctx_encoder...                   6
64  sentence-transformers/facebook-dpr-question_en...                   5

[65 rows x 2 columns]

In [ ]:
most_overlaps = overlaps.loc[0, 'transformer']

In [ ]:
most_overlaps

'sentence-transformers/LaBSE'

## Results

In [ ]:
def map_to_label(num_values):
  return np.asarray(['Weak' if item == 0 else 'Moderate' if item == 1 else 'Strong'  for item in num_values])

In [ ]:
def create_mapping_table(label, values, finance_labels, ml_labels):
  new_dataset = pd.DataFrame(columns=[label] + finance_labels)

  new_dataset[label] = ml_labels
  length = len(finance_labels)

  for num in range(length):
    column = finance_labels[num]
    to_index = (num + 1) * len(ml_labels)
    from_index = to_index - len(ml_labels)
    new_dataset[column] = map_to_label(values[from_index:to_index])

  return new_dataset

In [ ]:
# Define labels for the resulting tables
label = 'Mapping between finance and ML ethics'
finance_labels = ['Integrity', 'Objectivity', 'Competenece', 'Fairness', 'Confidentiality', 'Professionalism', 'Diligence']
ml_labels = ['Inclusive growth, sustainable development and weel-being', 'Human-centred values and fairness', 'Transparency and expalinability',
             'Robustness, security and safety', 'Accountability']

In [ ]:
# Print results for mappings between ethical principles based on long definitions
values = links_long[most_overlaps].values
create_mapping_table(label, values, finance_labels, ml_labels)

,Mapping between finance and ML ethics,Integrity,Objectivity,Competenece,Fairness,Confidentiality,Professionalism,Diligence
0,"Inclusive growth, sustainable development and ...",Weak,Weak,Weak,Weak,Weak,Weak,Weak
1,Human-centred values and fairness,Strong,Strong,Strong,Strong,Strong,Strong,Moderate
2,Transparency and expalinability,Weak,Moderate,Moderate,Strong,Strong,Strong,Strong
3,"Robustness, security and safety",Moderate,Moderate,Moderate,Moderate,Strong,Moderate,Strong
4,Accountability,Moderate,Weak,Weak,Weak,Moderate,Weak,Moderate

In [ ]:
# Print results for mappings between ethical principles based on short definitions
values = links_short[most_overlaps].values
create_mapping_table(label, values, finance_labels, ml_labels)

,Mapping between finance and ML ethics,Integrity,Objectivity,Competenece,Fairness,Confidentiality,Professionalism,Diligence
0,"Inclusive growth, sustainable development and ...",Moderate,Weak,Weak,Weak,Weak,Strong,Weak
1,Human-centred values and fairness,Strong,Strong,Weak,Strong,Strong,Strong,Moderate
2,Transparency and expalinability,Weak,Moderate,Weak,Weak,Strong,Weak,Moderate
3,"Robustness, security and safety",Strong,Strong,Moderate,Moderate,Strong,Strong,Moderate
4,Accountability,Strong,Weak,Weak,Moderate,Moderate,Moderate,Moderate

In [ ]:
# Print results for mappings between ethical principles based on human-based annotations
values = [1,1,2,1,2, 2,2,0,0,0, 0,0,1,1,1, 2,2,1,1,2, 0,1,0,2,0, 0,0,1,2,2, 1,2,0,2,1]
create_mapping_table(label, values, finance_labels, ml_labels)

,Mapping between finance and ML ethics,Integrity,Objectivity,Competenece,Fairness,Confidentiality,Professionalism,Diligence
0,"Inclusive growth, sustainable development and ...",Moderate,Strong,Weak,Strong,Weak,Weak,Moderate
1,Human-centred values and fairness,Moderate,Strong,Weak,Strong,Moderate,Weak,Strong
2,Transparency and expalinability,Strong,Weak,Moderate,Moderate,Weak,Moderate,Weak
3,"Robustness, security and safety",Moderate,Weak,Moderate,Moderate,Strong,Strong,Strong
4,Accountability,Strong,Weak,Moderate,Strong,Weak,Strong,Moderate